version: '3.5'
services:
  storage-server:
    build: server/
    image: omarzos/social-storage-server:latest
    container_name: phoros-social-storage-server
    env_file:
      - env/elastic.env
      - env/nebula.env
      - env/rabbitmq.env
    networks:
      - phoros_net
    # volumes:
    #   - 'storage-server:/code'
networks:
  phoros_net:
    external: true
# volumes:
#   storage-server:
#     driver: local


