version: '3.5'
services:
  storage-server:
    build: server/
    image: omarzos/social-storage-server:latest
    container_name: phoros-social-storage-server
    hostname: phoros-social-storage
    env_file:
      - env/elastic.env
      - env/nebula.env
      - env/rabbitmq.env
      - env/neo4j.env
    ports:
      - ${STORAGE_PORT_EXT}:8000
    networks:
      - phoros_net
      - phoros_public_net
    # for dev reasons..
    volumes:
      - ./server/:/code
networks:
  phoros_net:
    external: true
  phoros_public_net:
    name: phoros_public_net
    driver: bridge


